# Generated by Django 4.0.4 on 2022-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='email',
            field=models.EmailField(default='aileenzouyang@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='destination',
            name='message',
            field=models.TextField(default='no message'),
        ),
    ]
